#!/usr/bin/env python3

import os,sys,subprocess

args = sys.argv
#print(args)

if len(args) == 1 or args[1] == "--help":
    print("you can get tdos and pdos from mpid")
    print("job_mp mp-10 mp-21")
    print("")
    print("")

else:
    args.pop(0)
    print(args)
    for i in args:
        subprocess.run(["python3","createplot_from_mp.py",i])

